name: Build and run all tests
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: [1.18.x]
                os: [ubuntu-latest, macos-latest]

        steps:
            - name: Get the version
              id: get_version
              run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:8})

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Cache go modules
              uses: actions/cache@v1
              with:
                  path: ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
                  restore-keys: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}

            - name: Check out code
              uses: actions/checkout@v2

            - name: Get and verify dependencies
              run: go mod download && go mod verify

            - name: Go vet
              run: go vet ./...

            - name: Run tests
              run: go test ./...
